# Generated by Django 3.2.5 on 2021-09-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIDInv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_region', models.CharField(choices=[('sel', 'Open this menu to select your Region'), ('region1', 'AMRS'), ('region2', 'APAC'), ('region3', 'EMEA'), ('region4', 'LATAM')], max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('project_name', models.CharField(max_length=64)),
                ('project_comments', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('street_address1', models.CharField(max_length=256)),
                ('street_address2', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=64)),
                ('deal_status', models.CharField(max_length=64)),
                ('primary_contact', models.IntegerField()),
            ],
        ),
    ]
