# Generated by Django 3.2.5 on 2021-09-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DIDInv', '0002_userrequestform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRequestForm',
            new_name='UserRequestReg',
        ),
    ]
