# Generated by Django 3.2.5 on 2021-09-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIDInv', '0003_rename_userrequestform_userrequestreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestreg',
            name='deal_status',
            field=models.CharField(choices=[('option', 'open this select menu'), ('op1', 'Lead'), ('op2', 'Opportunity'), ('op3', 'In Contract'), ('op4', 'Won'), ('op5', 'Lost'), ('op6', 'On Hold'), ('op7', 'Cancelled')], max_length=64),
        ),
    ]
