# Generated by Django 3.2.5 on 2021-09-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIDInv', '0004_alter_userrequestreg_deal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIDProvison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_type', models.CharField(choices=[('option', 'open this select menu'), ('type1', 'DID'), ('type1', 'toll')], max_length=64)),
                ('country', models.CharField(choices=[('type1', 'USA'), ('type1', 'UK')], max_length=64)),
                ('state', models.CharField(choices=[('type1', 'NJ'), ('type1', 'NY')], max_length=64)),
                ('city', models.CharField(choices=[('type1', 'NJ'), ('type1', 'NY')], max_length=64)),
                ('max_count', models.IntegerField()),
                ('number_format', models.IntegerField()),
            ],
        ),
    ]
