# Generated by Django 3.2.5 on 2021-09-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIDInv', '0005_didprovison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didprovison',
            name='city',
            field=models.CharField(choices=[('city1', 'NJ'), ('city2', 'NY')], max_length=64),
        ),
        migrations.AlterField(
            model_name='didprovison',
            name='country',
            field=models.CharField(choices=[('country1', 'USA'), ('country2', 'UK')], max_length=64),
        ),
        migrations.AlterField(
            model_name='didprovison',
            name='number_type',
            field=models.CharField(choices=[('option', 'open this select menu'), ('type1', 'DID'), ('type2', 'toll')], max_length=64),
        ),
        migrations.AlterField(
            model_name='didprovison',
            name='state',
            field=models.CharField(choices=[('state1', 'NJ'), ('state2', 'NY')], max_length=64),
        ),
    ]
