# Generated by Django 3.2.5 on 2021-09-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIDInv', '0006_auto_20210907_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestreg',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='company_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='first_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='last_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='postal_code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='primary_contact',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='project_comments',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='project_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='street_address1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='userrequestreg',
            name='street_address2',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
