# Generated by Django 3.2.5 on 2021-09-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIDInv', '0007_auto_20210907_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIDNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_no', models.IntegerField()),
            ],
        ),
    ]
