# Generated by Django 3.2.5 on 2021-09-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIDInv', '0008_didnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestreg',
            name='select_region',
            field=models.CharField(choices=[('sel', 'Open this menu to select your Region'), ('AMRS', 'AMRS'), ('APAC', 'APAC'), ('EMEA', 'EMEA'), ('LATAM', 'LATAM')], max_length=64),
        ),
    ]
