# Generated by Django 3.2.5 on 2021-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIDInv', '0009_alter_userrequestreg_select_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIDAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_allocated', models.IntegerField()),
            ],
        ),
    ]
