# Generated by Django 3.2.5 on 2021-09-09 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIDInv', '0010_didallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didallocation',
            name='did_allocated',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d\\d-\\d\\d-\\d\\d-\\d\\d$')]),
        ),
    ]
