# Generated by Django 3.2.5 on 2021-09-09 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIDInv', '0012_alter_didallocation_did_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didallocation',
            name='did_allocated',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d$')]),
        ),
    ]
